services:
  - type: web
    name: nextkstar-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://nextkstar-backend.onrender.com 